name: Create and Write to Text Document

on: [push]

jobs:
  create-text-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Text Document
        run: |
          touch mynewdocument.txt
      - name: Write Message to Text Document
        run: |
          echo "Hello, World!" > mynewdocument.txt
      - name: Commit and Push Changes
        run: |
          git add mynewdocument.txt
          git commit -m "Add mynewdocument.txt"
          git push
